# Generated by Django 6.0 on 2025-12-28 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_users', '0001_initial'),
        ('inscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annees_scolaires', to='auth_users.etablissement')),
            ],
            options={
                'ordering': ['-libelle'],
                'unique_together': {('etablissement', 'libelle')},
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('seuil_deliberation', models.FloatField(default=10.0)),
                ('ordre', models.IntegerField(default=0)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='auth_users.etablissement')),
            ],
            options={
                'ordering': ['etablissement', 'ordre'],
                'unique_together': {('etablissement', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Reinscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_actuel', models.CharField(max_length=100)),
                ('niveau_vise', models.CharField(max_length=100)),
                ('dossier_pdf', models.FileField(upload_to='reinscriptions/')),
                ('bordereau', models.FileField(blank=True, null=True, upload_to='versements/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinscriptions', to='reinscription.anneescolaire')),
                ('concours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscription.concours')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_soumission'],
                'unique_together': {('utilisateur', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='ResultatNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.FloatField()),
                ('admis', models.BooleanField(default=False)),
                ('remarque', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_niveau', to='reinscription.anneescolaire')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='reinscription.niveau')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_niveau', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'niveau', 'annee_scolaire')},
            },
        ),
    ]
