# Generated by Django 6.0 on 2025-12-12 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
        ('reinscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('seuil_deliberation', models.FloatField(default=10.0)),
            ],
        ),
        migrations.AlterField(
            model_name='reinscription',
            name='concours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscription.concours'),
        ),
        migrations.CreateModel(
            name='ResultatNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.FloatField()),
                ('admis', models.BooleanField(default=False)),
                ('remarque', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_niveau', to='reinscription.anneescolaire')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='reinscription.niveau')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_niveau', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'niveau', 'annee_scolaire')},
            },
        ),
    ]
