# Generated by Django 6.0 on 2025-12-11 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prix', models.FloatField(default=0)),
                ('note_deliberation', models.FloatField(default=12.0)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_candidature', models.CharField(default='EN_ATTENTE', max_length=50)),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidat_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('statut_reinscription', models.CharField(default='NON', max_length=50)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to='inscription.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_requis', models.CharField(max_length=255)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaires', to='inscription.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionConcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='EN_ATTENTE', max_length=50)),
                ('justificatif_paiement', models.FileField(blank=True, null=True, upload_to='versements/')),
                ('numero_inscription', models.CharField(blank=True, max_length=20, null=True)),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscription.concours')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_inscription'],
                'unique_together': {('utilisateur', 'concours')},
            },
        ),
        migrations.CreateModel(
            name='ResultatConcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('classement', models.IntegerField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('admis', models.BooleanField(default=False)),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='inscription.concours')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_publication'],
                'unique_together': {('concours', 'utilisateur')},
            },
        ),
    ]
